<CENTER>
<H1> OTHER </H1>
</CENTER>

<H3> SUMMARY </H3>

The aim of this web site is to present a convenient entry point for
various activities, related to our simulations of stellar systems.
The GRAPE project, short for GRAvitational PipelinE, has produced
special purpose hardware for stellar dynamics, at a speed approaching
100 Teraflops.  We offer various open source software environments
such as NEMO and STARLAB for setting up, running, and analyzing
large-scale simulations in stellar dynamics.  Another open source
toolbox is the PARTIVIEW visualization package, which can be used on
various platforms, from laptops to virtual reality environments such
as the Cave at NCSA and the Hayden Planetarium in New York City.
Finally, we are in the process of setting up our ARCHIVE system, where
we plan to make the full results of our largest runs freely available
for guest observers. 
We are currently coordinating these efforts with various 
Virtual Observatory initiatives.
<P>
We also include the home page for MODEST (MOdeling DEnse STellar
systems),
a collaboration between various groups working in stellar dynamics,
stellar evolution, and stellar hydrodynamics.



<br>

<H3> HISTORY </H3>

For many years we have accumulated information about our hardware and
software projects at various websites, such as those for NEMO,
STARLAB, and GRAPE, three projects that started in the late eighties.
By the end of the year 2000, we decided to acquire our own domain name, 
manybody.org.  At first we simply used this site to provide pointers, but
we intend to provide a more structure set
of guides to the various projects we are involved in.  We will try to
update these introductory pages frequently.  Note for colleagues: if
you would like us to link your web site from an appropriate leaf in
our site tree, please send us your address and a very brief
description of the content of your site.

<H3> ACTIVITIES </H3>

<a href=AAS2002>Press release</a>, American Astronomical Society
meeting, January 2002


<H3> EXTERNAL LINKS </H3>

Other groups involved in large scale
     stellar dynamics simulations:
     <A HREF=http://zeus.ncsa.uiuc.edu:8080/GC3_Home_Page.html>
     GC3 Consortium</A>,
     <A HREF=http://www-hpcc.astro.washington.edu/>
     HPCC</A>,
     <A HREF=http://star-www.dur.ac.uk:80/~frazerp/virgo/virgo.html>
     Virgo Consortium</A>.
<br>
Virtual Observatory initiatives: <A HREF=http://bima.astro.umd.edu/nemo/nvo/>VO & Theory</A>,

