<CENTER> <H1>
				MODEST
</H1> </CENTER>


<H3> SUMMARY </H3>

MODEST stands for MOdeling DEnse STellar systems, and is a loosely
knit collaboration between various groups working in stellar dynamics,
stellar evolution, and stellar hydrodynamics.  Our aim is to provide a
software framework for large scale simulations of dense stellar
systems, in which existing codes for dynamics, stellar evolution, and
hydrodynamics can be easily coupled.
<p>
Though neither we nor our projects can possibly be described as
modest, we use our acronym to point out that we want to work with only
MODEST modifications of existing codes, to model dense stellar
systems.  So we can read the acronym also as MODifying Existing
STellar codes.
<p>
While many of us have talked for years about combining `live' stellar
evolution codes directly with N-body simulations, we have now reached
a consensus between various groups about standards and interfaces,
what is needed, and what is doable.  On this web site we will provide
up-to-date information about our activities, and pointers to various
projects in progress.
<p>
In order to participate in ongoing MODEST email discussions, see the
information provided below under LINKS.



<H3> HISTORY </H3>

In June, 2002, Piet Hut and Mike Shara organized a one-week workshop
in New York, at the American Museum of Natural History, bringing
together experts from stellar dynamics, stellar evolution, stellar
hydrodynamics, as well as other interested astrophysicists and
computer scientists.  At the end of the meeting, the acronym MODEST
was coined, and the meeting was renamed MODEST-1.  It was decided to
continue with a series of biannual meetings, with MODEST-2 in
Amsterdam, in December of 2002, and MODEST-3 in Melbourne to coincide
with the General Assembly of the International Astronomical Union.

<H3> WORKSHOPS </H3>

<UL>
<LI> <A HREF=modest-1.html>MODEST-1</A> (New York, USA, June 17-21,2002)
<LI> <A HREF=modest-2.html>MODEST-2</A> (Amsterdam, Holland, December 16-17, 2002)
<LI> <A HREF=modest-3.html>MODEST-3</A> (Melbourne, Australia,  July 9-11, 2003)
</UL>
See the summary paper for the MODEST-1 worskhop (to be provided here
soon).


<H3> PEOPLE </H3>

See the <a href=modest1-members.txt>list of participants</a> for MODEST-1


<H3> LINKS </H3>
<UL>
<LI> <A HREF=http://chandra.as.arizona.edu/~dave/tycho-intro.html>
     Tycho</A> (Dave Arnett's Stellar Evolution code)

<br><br>
<LI> <A HREF=http://faculty.vassar.edu/lombardi/triptych/>
     Triptych</A>: Simulates the collision of two stars, including the
     pre-collision orbits and the evolution of the collision product.
     Also has a <A
     HREF=http://143.229.45.51/cgi-bin/astro/triptych/triptych.pl>
     web interface</A>.
<br><br>

<LI> <A HREF=http://listmgr.cv.nrao.edu/mailman/listinfo/modest>
MODEST Mailing List</A> and the
 <A HREF=http://listmgr.cv.nrao.edu/pipermail/modest/>
list archive</A>. You can send email to
the list by using the email address: <b>modest@listmgr.cv.nrao.edu</b>

<LI> <A HREF="modest_star.html">Toy model</a> implementation of an
interface between stellar dynamics and stellar evolution.

<LI> The <a href="http://arXiv.org/abs/astro-ph/0207318">MODEST-1 summary paper</a>,
contains the main conclusion of our first workshop.

</UL>
